<%@ Page Language="C#" AutoEventWireup="true"
CodeBehind="DatabaseManager.aspx.cs"
Inherits="OExm.DatabaseManager" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">

    <title>Database Manager | OExm</title>

    <style>

        body{
            margin:0;
            padding:0;
            background:#f5f7fb;
            font-family:'Segoe UI';
        }

        .container{
            max-width:1400px;
            margin:30px auto;
            padding:20px;
        }

        .card{
            background:white;
            border-radius:12px;
            padding:25px;
            box-shadow:0 2px 12px rgba(0,0,0,.1);
        }

        h2{
            margin-top:0;
            color:#2563eb;
        }

        .dropdown,
        .search-box{
            padding:10px;
            border:1px solid #ccc;
            border-radius:8px;
        }

        .dropdown{
            width:300px;
        }

        .search-box{
            width:300px;
        }

        .btn{
            padding:10px 15px;
            border:none;
            border-radius:8px;
            cursor:pointer;
            background:#2563eb;
            color:white;
        }

        .btn:hover{
            background:#1d4ed8;
        }

        .gridview{
            width:100%;
            border-collapse:collapse;
            margin-top:15px;
        }

        .gridview th{
            background:#2563eb;
            color:white;
            padding:10px;
        }

        .gridview td{
            padding:10px;
            border:1px solid #ddd;
        }

        .gridview tr:nth-child(even){
            background:#f9fafb;
        }

        .gridview tr:hover{
            background:#eef4ff;
        }

        .toolbar{
            display:flex;
            gap:10px;
            margin-bottom:15px;
            flex-wrap:wrap;
        }

        .back-btn{
            display:inline-block;
            margin-bottom:15px;
            background:#6b7280;
            color:white;
            padding:10px 18px;
            border-radius:8px;
            text-decoration:none;
        }

        .back-btn:hover{
            background:#4b5563;
        }

    </style>

</head>

<body>

<form id="form1" runat="server">

<div class="container">

    <a href="AdminDashboard.aspx"
       class="back-btn">
        ← Back Dashboard
    </a>

    <div class="card">

        <h2>🗄 Database Manager</h2>

        <asp:Label
            ID="lblMessage"
            runat="server"
            ForeColor="Green"
            Font-Bold="true">
        </asp:Label>

        <br /><br />

        <div class="toolbar">

            <asp:DropDownList
                ID="ddlTables"
                runat="server"
                CssClass="dropdown"
                AutoPostBack="true"
                OnSelectedIndexChanged="ddlTables_SelectedIndexChanged">
            </asp:DropDownList>

            <asp:TextBox
                ID="txtSearch"
                runat="server"
                CssClass="search-box"
                placeholder="Search...">
            </asp:TextBox>

            <asp:Button
                ID="btnSearch"
                runat="server"
                Text="Search"
                CssClass="btn"
                OnClick="btnSearch_Click" />

        </div>

        <asp:Label
            ID="lblCount"
            runat="server"
            Font-Bold="true">
        </asp:Label>

        <br /><br />

        <asp:GridView
            ID="gvData"
            runat="server"
            CssClass="gridview"
            AutoGenerateColumns="true"
            AutoGenerateDeleteButton="true"
            AllowPaging="true"
            PageSize="20"
            OnPageIndexChanging="gvData_PageIndexChanging"
            OnRowDeleting="gvData_RowDeleting"
            EmptyDataText="No Records Found">
        </asp:GridView>

    </div>

</div>

</form>

</body>
</html>