<%@ Page Title="Database Manager" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="DatabaseManager.aspx.cs" Inherits="OExm.DatabaseManager" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadExtra" runat="server">
    <style>
        .db-toolbar {
            display: flex;
            gap: 10px;
            margin-bottom: 15px;
            flex-wrap: wrap;
        }
    </style>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <div class="card">
        <h2> Database Manager</h2>

        <asp:Label
            ID="lblMessage"
            runat="server"
            ForeColor="Green"
            Font-Bold="true">
        </asp:Label>

        <br /><br />

        <div class="db-toolbar">

            <asp:DropDownList
                ID="ddlTables"
                runat="server"
                CssClass="dropdown"
                AutoPostBack="true"
                OnSelectedIndexChanged="ddlTables_SelectedIndexChanged">
            </asp:DropDownList>

            <asp:TextBox
                ID="txtSearch"
                runat="server"
                CssClass="textbox"
                placeholder="Search...">
            </asp:TextBox>

            <asp:Button
                ID="btnSearch"
                runat="server"
                Text="Search"
                CssClass="btn btn-primary"
                OnClick="btnSearch_Click" />

        </div>

        <asp:Label
            ID="lblCount"
            runat="server"
            Font-Bold="true">
        </asp:Label>

        <br /><br />

        <asp:GridView
            ID="gvData"
            runat="server"
            CssClass="gridview"
            AutoGenerateColumns="true"
            AutoGenerateDeleteButton="true"
            AllowPaging="true"
            PageSize="20"
            OnPageIndexChanging="gvData_PageIndexChanging"
            OnRowDeleting="gvData_RowDeleting"
            EmptyDataText="No Records Found">
        </asp:GridView>

    </div>
</asp:Content>
